# Generated by Django 5.2.11 on 2026-06-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id_kategorie', models.BigAutoField(db_column='id_kategorie', primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'products_kategorie',
            },
        ),
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id_objednavka', models.BigAutoField(db_column='id_objednavka', primary_key=True, serialize=False)),
                ('datum', models.DateField()),
            ],
            options={
                'db_table': 'products_objednavka',
            },
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id_zakaznik', models.BigAutoField(db_column='id_zakaznik', primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('mesto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'products_zakaznik',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id_produkt', models.BigAutoField(db_column='id_produkt', primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sklad', models.IntegerField()),
                ('poznamka', models.CharField(blank=True, max_length=100)),
                ('id_kategorie', models.ForeignKey(db_column='id_kategorie', on_delete=django.db.models.deletion.CASCADE, to='products.kategorie')),
            ],
            options={
                'db_table': 'products_produkt',
            },
        ),
        migrations.CreateModel(
            name='PolozkaObjednavky',
            fields=[
                ('id_polozka', models.BigAutoField(db_column='id_polozka', primary_key=True, serialize=False)),
                ('mnozstvi', models.IntegerField()),
                ('id_objednavka', models.ForeignKey(db_column='id_objednavka', on_delete=django.db.models.deletion.CASCADE, to='products.objednavka')),
                ('id_produkt', models.ForeignKey(db_column='id_produkt', on_delete=django.db.models.deletion.CASCADE, to='products.produkt')),
            ],
            options={
                'db_table': 'products_polozkaobjednavky',
            },
        ),
        migrations.AddField(
            model_name='objednavka',
            name='id_zakaznik',
            field=models.ForeignKey(db_column='id_zakaznik', on_delete=django.db.models.deletion.CASCADE, to='products.zakaznik'),
        ),
    ]
