# Generated by Django 5.2.11 on 2026-06-03 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sklad', models.IntegerField()),
                ('poznamka', models.CharField(blank=True, max_length=100)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='PolozkaObjednavky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField()),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.objednavka')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produkt')),
            ],
        ),
        migrations.AddField(
            model_name='objednavka',
            name='zakaznik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.zakaznik'),
        ),
    ]
